"""empty message

Revision ID: 1a5ca5076a85
Revises: 
Create Date: 2024-11-23 21:07:59.752886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5ca5076a85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_foods', schema=None) as batch_op:
        batch_op.drop_column('food_image')

    # ### end Alembic commands ###
